apiVersion: v1
data:
  values.yaml: |
    bootstrap:
      wait_for_computes:
        enabled: true

    conf:
      ceph:
        enabled: true
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nova-values
  namespace: openstack
