apiVersion: v1
data:
  values.yaml: |
    conf:
      ceph:
        enabled: true
    bootstrap:
      wait_for_computes:
        enabled: true
    pod:
      env:
        - name: hypervisor_interface
          value: ens19
kind: ConfigMap
metadata:
  name: nova-values
  namespace: openstack
