apiVersion: v1
data:
  values.yaml: |
    conf:
      ceph:
        enabled: true
      libvirt:
        virt_type: qemu
        cpu_mode: none
    bootstrap:
      wait_for_computes:
        enabled: true
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nova-values
  namespace: openstack
