apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: neutron
  namespace: openstack
spec:
  releaseName: neutron
  interval: 5m
  chart:
    spec:
      chart: ./charts/neutron
      sourceRef:
        kind: GitRepository
        name: openstack-helm-fluxcd
        namespace: flux-system
      version: "2025.1.0"
  timeout: 15m
  valuesFrom:
    - kind: ConfigMap
      name: neutron-values
