apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openstack-base
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: openstack-helm-fluxcd
