apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: rook-ceph
  namespace: flux-system
spec:
  interval: 10m
  path: ../../apps/base/rook-ceph
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: rook-ceph
  dependsOn:
    - name: infrastructure
