apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx-cluster
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.8.3
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      admissionWebhooks:
        enabled: false
      kind: DaemonSet
      service:
        type: ClusterIP
      scope:
        enabled: false
      hostNetwork: true
      ingressClassResource:
        name: nginx-cluster
        controllerValue: k8s.io/ingress-nginx-cluster
        default: true
      ingressClass: nginx-cluster
      labels:
        app: ingress-api
