apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ceph-adapter-rook
  namespace: openstack
spec:
  interval: 10m
  chart:
    spec:
      chart: ./charts/ceph-adapter-rook
      sourceRef:
        kind: GitRepository
        name: openstack-helm-fluxcd
        namespace: flux-system
      version: "*" 
  install:
    createNamespace: true
  upgrade:
    remediation:
      retries: 3
