apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ceph-adapter-rook
  namespace: openstack
spec:
  chart:
    spec:
      chart: ./charts/ceph-adapter-rook
      sourceRef:
        kind: GitRepository
        name: openstack-helm-fluxcd
        namespace: flux-system
  interval: 5m
  values:
    namespace: rook-ceph
    conf:
      ceph:
        global:
          mon_host: "10.233.66.25:6789,10.233.65.213:6789,10.233.64.233:6789"
    manifests:
      configmap_bin: true
      configmap_templates: true
      configmap_etc: true
      job_storage_admin_keys: true
      job_namespace_client_key: true
