apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-ceph-operator-values
  namespace: rook-ceph
data:
  values.yaml: |
    image:
      repository: rook/ceph
      tag: v1.16.6
      pullPolicy: IfNotPresent
    crds:
      enabled: true
    nodeSelector: {}
    tolerations: []
    unreachableNodeTolerationSeconds: 5
    currentNamespaceOnly: false
    annotations: {}
    logLevel: INFO
    rbacEnable: true
    pspEnable: false
    priorityClassName:
    allowLoopDevices: true
    csi:
      enableRbdDriver: true
      enableCephfsDriver: false
      enableGrpcMetrics: false
      enableCSIHostNetwork: true
      enableCephfsSnapshotter: true
      enableNFSSnapshotter: true
      enableRBDSnapshotter: true
      enablePluginSelinuxHostMount: false
      enableCSIEncryption: false
      pluginPriorityClassName: system-node-critical
      provisionerPriorityClassName: system-cluster-critical
      rbdFSGroupPolicy: "File"
      cephFSFSGroupPolicy: "File"
      nfsFSGroupPolicy: "File"
      enableOMAPGenerator: false
      cephFSKernelMountOptions:
      enableMetadata: false
      provisionerReplicas: 1
      clusterName: ceph
      logLevel: 0
      sidecarLogLevel:
      rbdPluginUpdateStrategy:
      rbdPluginUpdateStrategyMaxUnavailable:
      cephFSPluginUpdateStrategy:
      nfsPluginUpdateStrategy:
      grpcTimeoutInSeconds: 150
      allowUnsupportedVersion: false
      csiRBDPluginVolume:
      csiRBDPluginVolumeMount:
      csiCephFSPluginVolume:
      csiCephFSPluginVolumeMount:
      provisionerTolerations:
      provisionerNodeAffinity:
      pluginTolerations:
      pluginNodeAffinity:
      enableLiveness: false
      cephfsGrpcMetricsPort:
      cephfsLivenessMetricsPort:
      rbdGrpcMetricsPort:
      csiAddonsPort:
      forceCephFSKernelClient: true
      rbdLivenessMetricsPort:
      kubeletDirPath:
      cephcsi:
        image:
      registrar:
        image:
      provisioner:
        image:
      snapshotter:
        image:
      attacher:
        image:
      resizer:
        image:
      imagePullPolicy: IfNotPresent
      cephfsPodLabels:
      nfsPodLabels:
      rbdPodLabels:
      csiAddons:
        enabled: false
        image: "quay.io/csiaddons/k8s-sidecar:v0.5.0"
      nfs:
        enabled: false
      topology:
        enabled: false
        domainLabels:
      readAffinity:
        enabled: false
        crushLocationLabels:
      cephFSAttachRequired: true
      rbdAttachRequired: true
      nfsAttachRequired: true
    enableDiscoveryDaemon: false
    cephCommandsTimeoutSeconds: "15"
    useOperatorHostNetwork:
    discover:
      toleration:
      tolerationKey:
      tolerations:
      nodeAffinity:
      podLabels:
      resources:
    disableAdmissionController: true
    hostpathRequiresPrivileged: false
    disableDeviceHotplug: false
    discoverDaemonUdev:
    imagePullSecrets:
    enableOBCWatchOperatorNamespace: true
    admissionController:
