apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  interval: 10m
  chart:
    spec:
      chart: rook-ceph
      version: v1.16.6
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: rook-ceph-operator-values
