apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: ceph
spec:
  interval: 10m
  chart:
    spec:
      chart: rook-ceph-cluster
      version: 1.16.6
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: rook-ceph-cluster-values
