apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ceph
  namespace: ceph
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/rook-ceph
      sourceRef:
        kind: GitRepository
        name: openstack-helm-fluxcd
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: rook-ceph-cluster-values
