apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ceph
  namespace: ceph
spec:
  interval: 5m
  chart:
    spec:
      chart: rook-ceph
      version: v1.16.6
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: rook-ceph-cluster-values
