resources:
  - namespaces/
#  - ../../infrastructure/base
#  - openstack-ingress-service/
#  - rook-ceph/
#  - ceph-adapter-rook/
#  - node-init/
#  - rabbitmq/
#  - mariadb/
#  - memecached/
#  - keystone/
#  - heat/
#  - glance/
#  - cinder/
#  - openvswitch/
#  - libvirt/
#  - placement/
#  - nova/
#  - neutron/
#  - horizon/



