apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  interval: 10m
  releaseName: rook-ceph
  chart:
    spec:
      chart: rook-ceph
      version: 1.13.2
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
  install:
    createNamespace: true
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: rook-ceph-values
