apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ceph-tools
  namespace: rook-ceph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rook-ceph-tools
  template:
    metadata:
      labels:
        app: rook-ceph-tools
    spec:
      serviceAccountName: rook-ceph-system
      containers:
        - name: rook-ceph-tools
          image: rook/ceph:v1.13.3
          command: ["/tini"]
          args: ["-g", "--", "/usr/local/bin/toolbox.sh"]
          securityContext:
            privileged: true

