apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-ceph-values
  namespace: rook-ceph
data:
  values.yaml: |
    cephClusterSpec:
      dashboard:
        enabled: true
      mon:
        count: 3
        allowMultiplePerNode: true
      storage:
        useAllNodes: true
        useAllDevices: true
