apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openvswitch
  namespace: openstack
spec:
  releaseName: openvswitch
  interval: 5m
  chart:
    spec:
      chart: ./charts/openvswitch
      sourceRef:
        kind: GitRepository
        name: openstack-helm-fluxcd
        namespace: flux-system
      version: "2025.1.0"
  timeout: 10m
  valuesFrom:
    - kind: ConfigMap
      name: openvswitch-values
