apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb
  namespace: openstack
spec:
  releaseName: mariadb
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: ./charts/mariadb
      sourceRef:
        kind: GitRepository
        name: openstack-helm-fluxcd
        namespace: flux-system
      version: "2025.1.0"
  values:
    pod:
      replicas:
        server: 1
    volume:
      enabled: false
      use_local_path_for_single_pod_cluster:
        enabled: true
