apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb
  namespace: openstack
spec:
  releaseName: mariadb
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: ./charts/mariadb
      sourceRef:
        kind: GitRepository
        name: openstack-helm-fluxcd
        namespace: flux-system
  values:
    pod:
      replicas:
        server: 1
