apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb
  namespace: openstack
spec:
  releaseName: mariadb
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: mariadb
      sourceRef:
        kind: GitRepository
        name: openstack-helm
        namespace: flux-system
      version: "*"  # optional: use specific version tag if pinned
  valuesFrom:
    - kind: ConfigMap
      name: mariadb-values-overrides  # this should contain merged output of helm osh get-values-overrides
      valuesKey: values.yaml
  values:
    pod:
      replicas:
        server: 1
